### ISSUE TITLE
Duplicates of symlinks

### ISSUE THREAD

**Issue by sergey-gru** [leahneukirchen/redo-c#27]
Api redo in this release seems that:

redo
redo-ifchange
redo-ifcreate
redo-hash

Here redo-ifchange, redo-ifcreate, redo-hash - are the symlinks

I offer to reduce these symlinks this way:

redo
redo --ifchange
redo --ifcreate
redo --hash

Here --ifchange, --ifcreate, --hash - are the firsts arguments of program redo

**Comment by leahneukirchen** [comment]
We cannot change this because people use the combined names in scripts already.
