### ISSUE TITLE
Boostrap instructions?

### ISSUE THREAD

**Issue by fingolfin** [leahneukirchen/redo-c#7]
It seems this project requires either an existing `redo`, or some manual intervention, to get going. Perhaps that could be stated in the README? That would be suuper helpful. I am really interesting in `redo`, but need something minimalistic, and the shell implementations supposedly are slow; this C version looks almost perfect: minimal, clean, self-contained... Except (??? at least as far as I could figure out, which of course just shows my limitations) for the bootstrapping).

<s>Moreover, it seems that even when using another `redo`, there are no instructions for recompiling `redo.c` (other than in a source code comment in `redo.c` itself)?</s> No, of course it's there, in `redo.c`, it's just that for some reason I can't seem to get it to run that, probably because I incorrectly bootstrapped?!

**Comment by fingolfin** [comment]
OK, I figured it out: for some reason, `.dep.redo` was missing; so after `touch .dep.redo` it worked well.

I guess I now kinda see the (or at least, "a") motivation for PR #6 (that's not to say I claim that PR is "correct" or "a good idea", just that I run into a similar pain point and wonder if there is a way to more resilient against that happening)

**Comment by leahneukirchen** [comment]
I'll add a build.sh.

**Comment by leahneukirchen** [comment]
Something like this maybe:

```
#!/bin/sh
# bootstrap script
set -ex
mkdir -p boot
(
cd boot
${CC:-cc} -g -Os -Wall -Wextra -Wwrite-strings -o redo ../redo.c
ln -sf redo redo-ifcreate
ln -sf redo redo-ifchange
ln -sf redo redo-always
)
PATH=$PWD/boot:$PATH redo all
```

**Comment by fingolfin** [comment]
Thank you!
